[algokit]
min_version = "v2.0.0"

[project]
type = 'workspace'
projects_root_path = 'projects'

[project.run]
build = ['algokit-utils-demo-retreat-2025-contracts', 'algokit-utils-demo-retreat-2025-frontend']
