# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: chris.kim@algorand.foundation
author_name: Chris Kim (Hyunggun)
cloud_provider: none
preset_name: production
project_name: algokit-utils-demo-retreat-2025-frontend

