# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: chris.kim@algorand.foundation
author_name: Chris Kim (Hyunggun)
contract_name: hello_world
deployment_language: typescript
preset_name: production
project_name: algokit-utils-demo-retreat-2025-contracts

