# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.4
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: chris.kim@algorand.foundation
author_name: Chris Kim (Hyunggun)
cloud_provider: none
contract_name: hello_world
deployment_language: typescript
preset_name: production
project_name: algokit-utils-demo-retreat-2025

